config/routes.rb
Rails.application.routes.draw do
  
  root to: redirect('/home')

  get 'home', to: 'pages#home', as: 'home'
  get 'history', to: 'pages#history', as: 'history'
  get 'team', to: 'pages#team', as: 'team'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    render :home
  end

  def team
    render :team
  end
  def history
    render :history
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shark Heads, Inc.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to 'SharkHeads', home_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Home', home_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Our Team', team_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Our History', history_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container mt-3">
      <%= yield %>
    </main>

    <footer class="footer mt-4 py-4" style="background-color: #f5f5f5">
      <div class="container small">
        <span class="text-muted">&copy; 2021 Shark Heads, Inc.</span>
      </div>
    </footer>

  </body>
</html>

app/views/pages/history.html.erb
<h1>Our History</h1>

<p>Shark Heads was founded in 2020 in Gulf Shores, Alabama.</p>

app/views/pages/home.html.erb
<h1>Shark Heads, Inc.</h1>

<p>
  We make giant shark heads!
</p>

<%= image_tag 'shark-heads.jpeg',
  class: 'w-100 rounded-circle shadow-lg d-block mx-auto',
  style: 'max-width: 28rem;'
%>

app/views/pages/team.html.erb
<h1>Our Team</h1>

<li>Mario</li>
<li>Also Mario</li>